TransbankDevelopers/transbank-sdk-dotnet

- Transbank/Onpay/Model/Refund.cs
- Transbank/Onpay/Model/Transaction.cs
- Transbank/Onpay/Net/Channel.cs
This was producing a deadlock in MVC projects.
> Convert async request to sync

- Transbank/Onepay/Enums/OnepayIntegrationType.cs
- Transbank/Onepay/Model/Refund.cs
- Transbank/Onepay/Model/Transaction.cs
- Transbank/Onepay/Onepay.cs
- Transbank/Onepay/Utils/OnepayRequestBuilder.cs
- TransbankTest/OnepayRequestBuilderTest.cs
- TransbankTest/TransbankEnumsTest.cs
> Update environments and app keys

- CHANGELOG.md
- README.md
- Transbank/Transbank.csproj
> Prepare Release 1.2.0

- README.md
Now the doc for all SDKs is consolidated on transbankdevelopers.cl,
avoiding tons of duplication and potential inconsistencies.
> Remove usage docs from this repository

- Transbank/Onepay/Enums/OnepayIntegrationType.cs
- TransbankTest/OnepayEnumsTest.cs
- TransbankTest/OnepayModelTest.cs
- Test case for checking the cart with item with negative amount
- Test case for checking validation when the total amount is negative
> Add test for checking edge case

- CHANGELOG.md
- Transbank/Transbank.csproj
See full changes https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v1.2.1...feat/prepare-release-1.3.0
> Prepare release 1.3.0

- CHANGELOG.md
- Transbank/Transbank.csproj
See full changes: https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v1.3.0...feat/prepare-release-2.0.0
> Prepare release 2.0.0

- CHANGELOG.md
- Transbank/Transbank.csproj
See full diff at: https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.0.0...feat/prepare-release-2.0.1
> Prepare Release 2.0.1

- TransbankTest/WebpayConfigTest.cs
Test was not calling the right method, also was not mark as Test Method so it was not being executed.
> Fix ForTesting Test

- CHANGELOG.md
- Transbank/Patpass/PatPassByWebpayNormal.cs
- Transbank/Transbank.csproj
See full diff at: [v2.0.1...feat/prepare-release-2.1.0](https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.0.1...feat/prepare-release-2.1.0)
Also Fix #61 #62 #63
> Prepare release 2.1.0

- CHANGELOG.md
- Transbank/Transbank.csproj
You can view full diff here [v2.1.0...prepare-release-2.2.0](https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.1.0...prepare-release-2.2.0)
> Prepare release 2.2.0

- CHANGELOG.md
- Transbank/Transbank.csproj
You can view full diff here [v2.2.0...prepare-release-2.2.1](https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.2.0...chore/prepare-release-2.2.1)
> Prepare release 2.2.1

- Transbank/WebpayRest/Common/CardDetail.cs
- Transbank/WebpayRest/Common/RequestService.cs
- Transbank/WebpayRest/WebpayPlus/Requests/CommitRequest.cs
- Transbank/WebpayRest/WebpayPlus/Requests/RefundRequest.cs
- Transbank/WebpayRest/WebpayPlus/Requests/StatusRequest.cs
- Transbank/WebpayRest/WebpayPlus/Responses/CommitResponse.cs
- Transbank/WebpayRest/WebpayPlus/Responses/RefundResponse.cs
- Transbank/WebpayRest/WebpayPlus/Responses/StatusResponse.cs
- Transbank/WebpayRest/WebpayPlus/Transaction.cs
> Add Plus Transaction Status (3)

- Transbank/WebpayRest/Common/TransactionDetail.cs
- Transbank/WebpayRest/WebpayPlus/MallTransaction.cs
- Transbank/WebpayRest/WebpayPlus/Requests/MallCreateRequest.cs
- Transbank/WebpayRest/WebpayPlus/Responses/CreateResponse.cs
- Transbank/WebpayRest/WebpayPlus/Responses/MallCreateResponse.cs
- Transbank/WebpayRest/WebpayPlus/WebpayPlus.cs
Add Webpay Plus Mall Create method
> Add Webpay Plus Mall Create

- Transbank/WebpayRest/WebpayPlus/WebpayPlus.cs
The method to configure deferred for testing was missing
> Add deferred configuration for testing

- Transbank/WebpayRest/WebpayPlus/MallTransaction.cs
- Transbank/WebpayRest/WebpayPlus/Requests/MallCommitRequest.cs
- Transbank/WebpayRest/WebpayPlus/Responses/MallCommitResponse.cs
Add Webpay Plus Mall Transaction commit
> Add Plus Mall Transaction commit

- Transbank/WebpayRest/WebpayPlus/MallTransaction.cs
- Transbank/WebpayRest/WebpayPlus/Requests/MallRefundRequest.cs
- Transbank/WebpayRest/WebpayPlus/Responses/MallRefundResponse.cs
This adds Webpay Plus Mall refund action.
`MallTransaction.refund` methods
Request and Response classes
> Add Mall Transaction Refund

- Transbank/Transbank.csproj
- Transbank/WebpayRest/WebpayPlus/Exceptions/MallStatusException.cs
- Transbank/WebpayRest/WebpayPlus/MallTransaction.cs
- Transbank/WebpayRest/WebpayPlus/Requests/MallStatusRequest.cs
- Transbank/WebpayRest/WebpayPlus/Responses/MallStatusResponse.cs
Add Webpay Plus Mall Transaction Status method and related classes
> Add plus mall status

- Transbank/WebpayRest/WebpayPlus/MallDeferredTransaction.cs
Implement Webpay Plus Mall Diferido Commit on rest SDK
> Add Commit to MallDeferredTransactions

- Transbank/WebpayRest/TransaccionCompleta/Common/Detail.cs
- Transbank/WebpayRest/TransaccionCompleta/Requests/CreateRequest.cs
- Transbank/WebpayRest/TransaccionCompleta/Responses/CreateResponse.cs
- Transbank/WebpayRest/TransaccionCompleta/Transaction.cs
add `create`method and base common
> add transaccion completa create method

- Transbank/WebpayRest/WebpayPlus/MallDeferredTransaction.cs
Create Refund and Status methods for Webpay Plus Mall Diferido on rest SDK
> Add refund and status for Webpay Plus Mall Diferido

- Transbank/Exceptions/TransactionInstallmentsException.cs
- Transbank/WebpayRest/TransaccionCompleta/Common/DeferredPeriods.cs
- Transbank/WebpayRest/TransaccionCompleta/FullTransaction.cs
- Transbank/WebpayRest/TransaccionCompleta/Requests/InstallmentsRequest.cs
- Transbank/WebpayRest/TransaccionCompleta/Responses/InstallmentsResponse.cs
add installments functions, also add installments exception to methods
> add transaction installments functions

- Transbank/Common/Options.cs
- Transbank/Onepay/Model/TransactionCommitResponse.cs
- Transbank/WebpayRest/WebpayPlus/DeferredTransaction.cs
- Transbank/WebpayRest/WebpayPlus/Exceptions/MallTransactionCaptureException.cs
- Transbank/WebpayRest/WebpayPlus/MallDeferredTransaction.cs
- Transbank/WebpayRest/WebpayPlus/Requests/MallCaptureRequest.cs
- Transbank/WebpayRest/WebpayPlus/Responses/MallCaptureResponse.cs
Add method Capture in DeferredMallTransaction class for Webpay Plus Mall Captura Diferida
> Add method Capture for WP Plus Mall Diferido

- Transbank/PatpassRest/PatpassComercio/Requests/StatusRequest.cs
- Transbank/WebpayRest/Oneclick/MallTransaction.cs
- Transbank/WebpayRest/TransaccionCompleta/FullTransaction.cs
- Transbank/WebpayRest/TransaccionCompletaMall/MallFullTransaction.cs
- Transbank/WebpayRest/WebpayPlus/MallDeferredTransaction.cs
add missing headers to other methods, prevents compilation errors
> fix replace headers after merge others methods

- CHANGELOG.md
- Transbank/Transbank.csproj
You can view full diff here https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.2.1...chore/prepare-release-2.3.0
> Chore/prepare release 2.3.0

- Transbank/Transbank.csproj
Nuget package is missing Transbank Icon.
> Update Nuget Package Icon

- CHANGELOG.md
- Transbank/Transbank.csproj
You can view full diff here [v2.3.0...chore/prepare-release-2.4.0](https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.3.0...chore/prepare-release-2.4.0)
> Prepare release 2.4.0

- Transbank/Onepay/Utils/HttpHelper.cs
- Transbank/Onepay/Utils/IRequestBuilder.cs
- Transbank/Onepay/Utils/ISignUtil.cs
- Transbank/Onepay/Utils/LICENSE
- Transbank/Onepay/Utils/NOTICE
- Transbank/Onepay/Utils/OnepayRequestBuilder.cs
- Transbank/Onepay/Utils/OnepaySignUtil.cs
- Transbank/Onepay/Utils/Sigv4util.cs
Add missing files and comment into the socket utils
> Add missing files and comments

- README.md
Created troubleshooting section with its first entry (CryptographicException: Invalid algorithm specified)
> Create troubleshoorint section in README

- CHANGELOG.md
- Transbank/Transbank.csproj
This PR will triger te release of version 2.5.0 including rest support.
> Prepare release 2.5.0

- Transbank/WebpayRest/WebpayPlus/DeferredTransaction.cs
Temporal patch.
This should be scraped and https://github.com/TransbankDevelopers/transbank-sdk-dotnet/pull/124 used instead when we can make breaking changes
> Add missing headers to deferred tx

- CHANGELOG.md
- Transbank/Transbank.csproj
Full diff https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v2.6.0...chore/prepare-release-3.0.0
> Prepare release 3.0.0

- CHANGELOG.md
- Transbank/Transbank.csproj
Full diff https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v3.0.0...chore/prepare-release-3.0.1
> Prepare release 3.0.1

- CHANGELOG.md
- README.md
- Transbank/Transbank.csproj
Full diff https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v3.0.1...master
> add 4.0.0 changelog

- Transbank/Transbank.csproj
Full diff https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v4.0.0...master
> add 4.0.1 changelog

- CHANGELOG.md
- Transbank/Transbank.csproj
Full diff https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v4.0.1...master
> add 5.0.0 changelog

- CHANGELOG.md
- Transbank/Transbank.csproj
full diff: https://github.com/TransbankDevelopers/transbank-sdk-dotnet/compare/v5.0.0...master
> Chore/prepare release 6.0.0

- Transbank/Transbank.csproj
- update libraries for security reasons
> update library for security reasons

- Transbank/Common/ExceptionHandler.cs
This PR fix the Code assignation for Transbank Exceptions.
> fix: exception code

- appveyor.yml
> chore: update nuget api key

- Transbank/Webpay/TransaccionCompletaMall/Common/MallInstallmentsDetailsResponse.cs
- Transbank/Webpay/TransaccionCompletaMall/MallFullTransaction.cs
- Transbank/Webpay/TransaccionCompletaMall/Responses/MallInstallmentsResponse.cs
This PR fix the mall full transaction return from installments method.
> fix: mall full transaction installments

- CHANGELOG.md
- Transbank/Transbank.csproj
- Transbank/Webpay/TransaccionCompletaMall/Common/MallInstallmentsDetailsResponse.cs
- Transbank/Webpay/TransaccionCompletaMall/MallFullTransaction.cs
- Transbank/Webpay/TransaccionCompletaMall/Responses/MallInstallmentsResponse.cs
Release from version 7.0.1
Includes the following changes:
- Fix return of installments method Full transaction mall
> chore: prepare release 7.0.1

- Transbank/Common/Options.cs
- Transbank/Common/RequestService.cs
This version includes the following changes:
- Add default timeout of 10 minutes in options.
- Add custom timeout in options.
- Timeout configuration in RequestService.cs
> Case with 5 seconds
> Constructor with 5 seconds configured by default (example)
> feat: add request timeout 

- README.md
- Tests/Tests.csproj
- Transbank/Transbank.csproj
- appveyor.yml
This PR:
* update newtonsoft library
* update test project and test libraries
> chore: update libraries

- appveyor.yml
* move nuget secure api_key to appveyor environment variable
> chore: update appveyor

- .github/workflows/build.yml
- .gitignore
- CHANGELOG.md
- README.md
- Tests/OneclickMallInfoBin.cs
- Tests/Tests.csproj
- Transbank/Exceptions/MallQueryBinException.cs
- Transbank/Transbank.csproj
- Transbank/Webpay/Oneclick/MallInfoBin.cs
- Transbank/Webpay/Oneclick/Requests/MallQueryBinRequest.cs
- Transbank/Webpay/Oneclick/Responses/MallQueryBinResponse.cs
- sonar-project.properties
PR for the release of version 7.2.0
This release includes:
- Add new class to query info bin on OneClick
- Update outdated test dependencies
> release: prepare release 7.2.0

- CHANGELOG.md
This PR update the release date in changelog file.
> docs: update release date
